# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = "[❯](bold green)" # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[❯](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false


# Enable username module
[username]
show_always = true  # Always show the username
format = "[@](bold yellow)[$user]($style) [➜](bold green) "  # How the username appears

[status]
disabled = true

[python]
symbol = "[⌉](bold bright-blue)⌊ "
format = '(via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style))'
version_format = "v${raw}"
style = "bold bright-yellow"
